cluster:
  name: ${CLUSTER_NAME}

node:
  master: ${NODE_MASTER}
  data: ${NODE_DATA}
  name: ${NODE_NAME}
  ingest: ${NODE_INGEST}
  max_local_storage_nodes: ${MAX_LOCAL_STORAGE_NODES}

network.host: ${NETWORK_HOST}

path:
  data: /data/data
  logs: /data/log

bootstrap:
  memory_lock: ${MEMORY_LOCK}

http:
  enabled: ${HTTP_ENABLE}
  compression: true
  cors:
    enabled: ${HTTP_CORS_ENABLE}
    allow-origin: ${HTTP_CORS_ALLOW_ORIGIN}

discovery:
  zen:
    ping.unicast.hosts: ${DISCOVERY_SERVICE}
    minimum_master_nodes: ${NUMBER_OF_MASTERS}

thread_pool:
  index:
    queue_size: ${THREAD_POOL_INDEX_QUEUE_SIZE}
  bulk:
    size: ${THREAD_POOL_BULK_SIZE}
    queue_size: ${THREAD_POOL_BULK_QUEUE_SIZE}

indices:
  memory:
    index_buffer_size: ${INDICES_MEMORY_INDEX_BUFFER_SIZE}
